// Code generated by protoc-gen-go.
// source: ip_event.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	ip_event.proto

It has these top-level messages:
	IpEvent
*/
package main

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type IpEvent struct {
	AppSha256        *string `protobuf:"bytes,1,req,name=app_sha256" json:"app_sha256,omitempty"`
	Ip               *int64  `protobuf:"varint,2,req,name=ip" json:"ip,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IpEvent) Reset()         { *m = IpEvent{} }
func (m *IpEvent) String() string { return proto.CompactTextString(m) }
func (*IpEvent) ProtoMessage()    {}

func (m *IpEvent) GetAppSha256() string {
	if m != nil && m.AppSha256 != nil {
		return *m.AppSha256
	}
	return ""
}

func (m *IpEvent) GetIp() int64 {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return 0
}

func init() {
}
